In [15]:
! python3 -m pip install PTable

Requirement already satisfied: PTable in /Users/kristinngodfrey/miniconda3/lib/python3.7/site-packages (0.9.2)

In [19]:
import pandas as pd

algs = { 
            'FCFS': ["P1","P1","P1","P1","P2","P2","P2","P2","P2","P2","P2","P2","P2","P2","P2","P3","P3","P3","P3","P3","P3","P3","P3","P4","P4","P4","P4","P4","P5","P5","P5","P5"],
            'SJF': ["P1","P1","P1","P1","P3","P3","P3","P3","P3","P3","P3","P3","P2","P2","P2","P2","P2","P2","P2","P2","P2","P2","P2","P5","P5","P5","P5","P4","P4","P4","P4","P4"],
            'SRTF': ["P1","P1","P1","P1","P3","P3","P3","P3","P3","P3","P3","P3","P2","P2","P4","P4","P4","P4","P4","P5","P5","P5","P5","P2","P2","P2","P2","P2","P2","P2","P2","P2",],
            'RR': ["P1","P1","P1","P1","P2","P2","P2","P2","P3","P3","P3","P3","P2","P2","P2","P2","P3","P3","P3","P3","P4","P4","P4","P4","P2","P2","P2","P5","P5","P5","P5","P4"],
            'RR-prio': ["P1","P1","P1","P1","P3","P3","P3","P3","P3","P3","P3","P3","P2","P2","P4","P4","P4","P4","P5","P5","P5","P5","P4","P2","P2","P2","P2","P2","P2","P2","P2","P2",]
}
algs = pd.DataFrame(algs)
algs

   FCFS SJF SRTF  RR RR-prio
0    P1  P1   P1  P1      P1
1    P1  P1   P1  P1      P1
2    P1  P1   P1  P1      P1
3    P1  P1   P1  P1      P1
4    P2  P3   P3  P2      P3
5    P2  P3   P3  P2      P3
6    P2  P3   P3  P2      P3
7    P2  P3   P3  P2      P3
8    P2  P3   P3  P3      P3
9    P2  P3   P3  P3      P3
10   P2  P3   P3  P3      P3
11   P2  P3   P3  P3      P3
12   P2  P2   P2  P2      P2
13   P2  P2   P2  P2      P2
14   P2  P2   P4  P2      P4
15   P3  P2   P4  P2      P4
16   P3  P2   P4  P3      P4
17   P3  P2   P4  P3      P4
18   P3  P2   P4  P3      P5
19   P3  P2   P5  P3      P5
20   P3  P2   P5  P4      P5
21   P3  P2   P5  P4      P5
22   P3  P2   P5  P4      P4
23   P4  P5   P2  P4      P2
24   P4  P5   P2  P2      P2
25   P4  P5   P2  P2      P2
26   P4  P5   P2  P2      P2
27   P4  P4   P2  P5      P2
28   P5  P4   P2  P5      P2
29   P5  P4   P2  P5      P2
30   P5  P4   P2  P5      P2
31   P5  P4   P2  P4      P2

In [2]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [18]:
from prettytable import PrettyTable
    
x = PrettyTable()

x.field_names = ["City name", "Area", "Population", "Annual Rainfall"]

x.add_row(["Adelaide", 1295, 1158259, 600.5])
x.add_row(["Brisbane", 5905, 1857594, 1146.4])
x.add_row(["Darwin", 112, 120900, 1714.7])
x.add_row(["Hobart", 1357, 205556, 619.5])
x.add_row(["Sydney", 2058, 4336374, 1214.8])
x.add_row(["Melbourne", 1566, 3806092, 646.9])
x.add_row(["Perth", 5386, 1554769, 869.4])

x

ModuleNotFoundError: No module named 'prettytable'